### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by mmahadevan-okta** [dgmckenna/InvestingCSVtoPivotReports#1]
You've built exactly what I need.  :)  

I suspect this may be a macOS related issue.  Any ideas?

```
15:26 $ python ./InvestingCSVtoPivotReports.py
Traceback (most recent call last):
  File "./InvestingCSVtoPivotReports.py", line 50, in <module>
    from openpyxl.cell import get_column_letter
ImportError: cannot import name get_column_letter
```

**Comment by mmahadevan-okta** [comment]
Ok, I think I got this one.  The [`import openpyxl`](https://github.com/dgmckenna/InvestingCSVtoPivotReports/blob/master/InvestingCSVtoPivotReports.py#L48) statement needs to be `from openpyxl.utils import get_column_letter`

**Comment by dgmckenna** [comment]
Hello, I'm glad you like it! I have a version of the script which works for the "new" webbroker. I'll post it within a few days.

If you've kept .csv files you downloaded with the old webbroker, there's a way to migrate that data into the excel file, and then switchover to the new version of the script.
