### ISSUE TITLE
Named Ranges no longer reference-able from PythonPivot excel

### ISSUE THREAD

**Issue by dgmckenna** [dgmckenna/InvestingCSVtoPivotReports#3]
For some reason, I cannot access the named range in the PythonExcel file, from my PythonPivot file.

I tried setting the data source in the PythonPivot file pivot table to be:
[PythonExcel.xlsx]SourceData!PivotData
This does not work.

I tried
[PythonExcel.xlsx]!PivotData

This does work, but somehow the named range isn't in an acceptable form for the pivot table. I've also seen some odd behaviour in excel where the named range seems to move on it's own... For now, the pivot table report must be regenerated manually to look at new data added to the file and the previous ability to link to named ranges in the PythonExcel file does not work anymore.

Given all the trouble with excel, it's tempting to make a google docs version of this which may have fewer issues and better libraries.

**Comment by mmahadevan-okta** [comment]
Agreed. The Google Sheets seems like a neat way to go... I have been exploring that as well. I may be able help as well.

**Comment by dgmckenna** [comment]
Due to the issues with named ranges, I found the current program un-usable.

I've created a branch called revert which went back to some older code. If openpyxl version 2.3.5 is installed it all works fine. This is usable, but not ideal.

I'm going to look at not using excel but instead using google sheets, which has some other advantages as well.

**Comment by dgmckenna** [comment]
Actually, google sheets pivot tables are ugly, a bit slow, and not as friendly.

Instead, I'm thinking of doing the following:
1. python script looks at CSV's, and converts to a consolidated CSV file with no asset allocation in it.
2. Excel file, links to CSV file as "external data source". There are some config options in excel which need to be different from default to make this easier like "don't prompt for file location on refresh" among others.
3. The CSV data loaded into the excel file, is loaded into the Power Pivot data model
4. A separate "table" in excel is created which is loaded into the data model. This table has the asset allocation information.
5. The two tables are linked in the data model, allowing you to do a pivot table on them both.
6. Offline data from another non-TD CSV file account could be loaded from a csv or by other means.

This simplifies the python scripting, but requires a more elaborate, manually built excel file.
If you have a relationship, but there is no category for a certain security it will show in the pivot table as "blank".

This seems to be the easiest, fastest way to get analytics out of the csv's. If you have any ideas or other software that you know of please let me know.

**Comment by mmahadevan-okta** [comment]
I've been thinking about this issue but have not really done anything about it.  But I think the Google Sheets (or this https://cloud.google.com/datastore/ ) maybe the place to consolidate the CSVs but once that is done, use something like https://d3js.org to provide visualization.  This could be more work than needed. :)    Perhaps a summer side-project for **us**...
